local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 1
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.02

  observation_sources: laser_1

  laser_1: {sensor_frame: laser_1_scan , data_type: LaserScan, topic: laser_scanner/scan, marking: true, clearing: true, obstacle_range: 5.0, raytrace_range: 8.0}
